=== PennyLaneAI/qml/demonstrations/metadata_schemas/demo.metadata.schema.0.1.0.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/PennyLaneAI/qml/tree/master/demonstrations/metadata_schemas/demo.metadata.schema.0.1.0.json",
    "title": "Demo Metadata",
    "description": "A QML demo's metadata",
    "type": "object",
    "properties": {
      "title": {
        "description": "The title of the demo.",
        "type": "string",
        "minLength": 2
      },
      "authors": {
        "description": "The author(s) of the demo.",
        "type": "array",
        "items": {
          "$ref": "./author.schema.0.1.0.json"
        }
      },
      "dateOfPublication": {
        "description": "The date on which the demo was first published, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string"
      },
      "dateOfLastModification": {
        "description": "The date on which the demo was last modified, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string"
      },
      "categories": {
        "description": "An array of the categories that this demo is in.",
        "type": "array",
        "items": {
          "enum": ["Getting Started", "Optimization", "QML", "Quantum Chemistry", "Quantum Computing", "Community"]
        }
      },
      "tags": {
        "description": "An array of the tags that the demo has. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "previewImages": {
        "description": "An array of the different images that can be used as previews for this demo - e.g., thumbnails, social media cards (perhaps of different aspect ratios).",
        "$ref": "./preview.image.schema.0.1.0.json"
      },
      "seoDescription": {
        "description": "A description of the demo suitable for SEO purposes. Ideally this should be less than 150 characters, but this is not a strict limit. It should be a full, grammatically-correct sentence ending in a full stop.",
        "type": "string",
        "minLength": 2
      },
      "doi": {
        "description": "The DOI for the demo.",
        "type": "string"
      },
      "canonicalURL": {
        "description": "The canonical URL for the demo. Sometimes there might be more than one URL that points to a given page on a website. The canonical URL defines which of these should be thought of as the primary or main one.",
        "type": "string",
        "minLength": 10
      },
      "references": {
        "description": "An array of the references used for the demo.",
        "$ref": "./reference.schema.0.1.0.json"
      },
      "basedOnPapers": {
        "description": "An array of the DOIs for the papers the demo is based on. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "referencedByPapers": {
        "description": "An array of the DOIs of any papers that reference the demo. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "relatedContent": {
        "description": "An array of objects describing the content related to the demo. An empty array is allowed.",
        "$ref": "./related.content.schema.0.1.0.json"
      }
    },
    "required": [
      "title", "authors", "dateOfPublication", "dateOfLastModification", "categories", "tags", "previewImages", "seoDescription", "doi", "canonicalURL", "references", "basedOnPapers", "referencedByPapers", "relatedContent"
    ]
  }

=== PennyLaneAI/qml/demonstrations/tutorial_spsa.metadata.json
{
    "title": "Optimization using SPSA",
    "authors": [
        {
            "id": "antal_szava"
        },
        {
            "id": "david_wierichs"
        }
    ],
    "dateOfPublication": "2023-03-19T00:00:00",
    "dateOfLastModification": "2023-02-23T00:00:00",
    "categories": [],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "https://pennylane.ai/qml/_images/spsa_mntn.png"
        }
    ],
    "seoDescription": "Use the simultaneous perturbation stochastic approximation algorithm to optimize variational circuits in PennyLane.",
    "doi": "",
    "canonicalURL": "https://pennylane.ai/qml/demos/tutorial_spsa.html",
    "references": [
        {
            "id": "spall_overview",
            "title": "An Overview of the Simultaneous Perturbation Method for Efficient Optimization",
            "authors": "James C. Spall",
            "year": "1998",
            "journal": "",
            "doi": "",
            "url": "https://www.jhuapl.edu/SPSA/PDF-SPSA/Spall_An_Overview.PDF"
        },
        {
            "id": "spall_implementation",
            "title": "Implementation of the simultaneous perturbation algorithm for stochastic optimization",
            "authors": "J. C. Spall",
            "year": "1998",
            "journal": "IEEE Transactions on Aerospace and Electronic Systems",
            "volume": "34",
            "number": "3",
            "pages": "817-823",
            "doi": "10.1109/7.705889",
            "url": ""
        },
        {
            "id": "spall_hessian",
            "title": "Adaptive stochastic approximation by the simultaneous perturbation method",
            "authors": "J. C. Spall",
            "year": "2020",
            "journal": "IEEE Transactions on Automatic Control",
            "volume": "45",
            "number": "10",
            "pages": "1839-1853",
            "doi": "10.1109/TAC.2000.880982",
            "url": ""
        },
        {
            "id": "qnspsa",
            "title": "Simultaneous Perturbation Stochastic Approximation of the Quantum Fisher Information",
            "authors": "J. Gacon, C. Zoufal, G. Carleo, and S. Woerner",
            "year": "2021",
            "journal": "Quantum",
            "doi": "",
            "url": "https://quantum-journal.org/papers/q-2021-10-20-567/"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_vqe",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_vqe_qng",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "qnspsa",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_stochastic_parameter_shift.metadata.json
{
    "title": "The stochastic parameter-shift rule",
    "authors": [
        {
            "id": "nathan_killoran"
        }
    ],
    "dateOfPublication": "2020-05-25T00:00:00",
    "dateOfLastModification": "2021-01-15T00:00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "stochastic_parameter_shift_thumbnail.png"
        }
    ],
    "seoDescription": "",
    "doi": "",
    "canonicalURL": "https://pennylane.ai/qml/demos/tutorial_stochastic_parameter_shift.html",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": []
}

=== PennyLaneAI/qml/demonstrations/tutorial_fermionic_operators.metadata.json
{
    "title": "Fermionic operators",
    "authors": [
        {
            "id": "soran_jahangiri"
        }
    ],
    "dateOfPublication": "2023-06-27T00:00:00",
    "dateOfLastModification": "2023-06-27T00:00:00",
    "categories": [
        "Quantum Chemistry"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_images/fermionic_operators.jpg"
        }
    ],
    "seoDescription": "Construct Hamiltonians and other observables using fermionic creation and annihilation operators.",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_fermionic_operators",
    "references": [
        {
            "id": "surjan",
            "title": "Second Quantized Approach to Quantum Chemistry",
            "authors": "Peter R. Surjan",
            "year": "1989",
            "publisher": "Springer-Verlag",
            "doi": "",
            "url": ""
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_quantum_chemistry",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_vqe",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_backprop.metadata.json
{
    "title": "Quantum gradients with backpropagation",
    "authors": [
        {
            "id": "josh_izaac"
        }
    ],
    "dateOfPublication": "2020-08-11T00:00:00+00:00",
    "dateOfLastModification": "2024-01-01T00:00:00+00:00",
    "categories": [
        "Getting Started"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/regular_demo_thumbnails/thumbnail_quantum_gradients_backpropagation.png"
        }
    ],
    "seoDescription": "Using backpropagation can speed up training of quantum circuits compared to the parameter-shift ruleâ€”if you are using a simulator.",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_backprop",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_quantum_natural_gradient",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_pulse_programming101.metadata.json
{
    "title": "Differentiable pulse programming with qubits in PennyLane",
    "authors": [
        {
            "id": "korbinian_kottmann"
        }
    ],
    "dateOfPublication": "2023-03-08T00:00:00",
    "dateOfLastModification": "2023-03-08T00:00:00",
    "categories": [],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_images/thumbnail_tutorial_pulse_programming.png"
        },
        {
            "type": "hero_image",
            "uri": "/_static/hero_illustrations/thumbnail_large_pulse_programming.png"
        }
    ],
    "seoDescription": "Simulating differentialble pulse programs in PennyLane with qubits",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_pulse_programming101",
    "references": [
        {
            "id": "Mitei",
            "title": "Gate-free state preparation for fast variational quantum eigensolver simulations: ctrl-VQE",
            "authors": "Oinam Romesh Meitei, Bryan T. Gard, George S. Barron, David P. Pappas, Sophia E. Economou, Edwin Barnes, Nicholas J. Mayhall",
            "year": "2020",
            "publisher": "",
            "doi": "",
            "url": "https://arxiv.org/abs/2008.04302"
        },
        {
            "id": "Sheldon2016",
            "title": "Procedure for systematically tuning up crosstalk in the cross resonance gate",
            "authors": "Sarah Sheldon, Easwar Magesan, Jerry M. Chow, Jay M. Gambetta",
            "year": "2016",
            "publisher": "",
            "doi": "",
            "url": "https://arxiv.org/abs/1603.04821"
        },
        {
            "id": "Leng2022",
            "title": "Differentiable Analog Quantum Computing for Optimization and Control",
            "authors": "Jiaqi Leng, Yuxiang Peng, Yi-Ling Qiao, Ming Lin, Xiaodi Wu",
            "year": "2022",
            "publisher": "",
            "doi": "",
            "url": "https://arxiv.org/abs/2210.15812"
        },
        {
            "id": "Asthana2022",
            "title": "Minimizing state preparation times in pulse-level variational molecular simulations",
            "authors": "Ayush Asthana, Chenxu Liu, Oinam Romesh Meitei, Sophia E. Economou, Edwin Barnes, Nicholas J. Mayhall",
            "year": "2022",
            "publisher": "",
            "doi": "",
            "url": "https://arxiv.org/abs/2203.06818"
        },
        {
            "id": "Russell2016",
            "title": "Quantum Control Landscapes Are Almost Always Trap Free",
            "authors": "Benjamin Russell, Herschel Rabitz, Rebing Wu",
            "year": "2016",
            "publisher": "",
            "doi": "",
            "url": "https://arxiv.org/abs/1608.06198"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": []
}

=== PennyLaneAI/qml/demonstrations/tutorial_qaoa_maxcut.metadata.json
{
    "title": "QAOA for MaxCut",
    "authors": [
        {
            "id": "angus_lowe"
        }
    ],
    "dateOfPublication": "2019-10-11T00:00:00",
    "dateOfLastModification": "2021-04-13T00:00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "qaoa_maxcut_partition.png"
        }
    ],
    "seoDescription": "",
    "doi": "",
    "canonicalURL": "https://pennylane.ai/qml/demos/tutorial_qaoa_maxcut.html",
    "references": [
        {
            "id": "",
            "title": "",
            "authors": "",
            "year": "",
            "journal": "",
            "doi": "",
            "url": ""
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/spsa.metadata.json
{
    "title": "Optimization using SPSA",
    "authors": [
        {
            "id": "antal_szava"
        }
    ],
    "dateOfPublication": "2021-03-19T00:00:00",
    "dateOfLastModification": "2022-09-13T00:00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "spsa_mntn.png"
        }
    ],
    "seoDescription": "",
    "doi": "",
    "canonicalURL": "https://pennylane.ai/qml/demos/spsa.html",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": []
}

=== PennyLaneAI/qml/demonstrations/tutorial_quantum_metrology.metadata.json
{
    "title": "Variationally optimizing measurement protocols",
    "authors": [
        {
            "id": "johannes_jakob_meyer"
        }
    ],
    "dateOfPublication": "2020-06-18T00:00:00",
    "dateOfLastModification": "2021-11-18T00:00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "illustration1.png"
        }
    ],
    "seoDescription": "",
    "doi": "",
    "canonicalURL": "https://pennylane.ai/qml/demos/tutorial_quantum_metrology.html",
    "references": [
        {
            "id": "",
            "title": "",
            "authors": "",
            "year": "",
            "journal": "",
            "doi": "",
            "url": ""
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "",
            "weight": 1.0
        }
    ]
}
