=== PennyLaneAI/qml/demonstrations/metadata_schemas/demo.metadata.schema.0.1.0.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/PennyLaneAI/qml/tree/master/demonstrations/metadata_schemas/demo.metadata.schema.0.1.0.json",
    "title": "Demo Metadata",
    "description": "A QML demo's metadata",
    "type": "object",
    "properties": {
      "title": {
        "description": "The title of the demo.",
        "type": "string",
        "minLength": 2
      },
      "authors": {
        "description": "The author(s) of the demo.",
        "type": "array",
        "items": {
          "$ref": "./author.schema.0.1.0.json"
        }
      },
      "dateOfPublication": {
        "description": "The date on which the demo was first published, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string"
      },
      "dateOfLastModification": {
        "description": "The date on which the demo was last modified, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string"
      },
      "categories": {
        "description": "An array of the categories that this demo is in.",
        "type": "array",
        "items": {
          "enum": ["Getting Started", "Optimization", "QML", "Quantum Chemistry", "Quantum Computing", "Community"]
        }
      },
      "tags": {
        "description": "An array of the tags that the demo has. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "previewImages": {
        "description": "An array of the different images that can be used as previews for this demo - e.g., thumbnails, social media cards (perhaps of different aspect ratios).",
        "$ref": "./preview.image.schema.0.1.0.json"
      },
      "seoDescription": {
        "description": "A description of the demo suitable for SEO purposes. Ideally this should be less than 150 characters, but this is not a strict limit. It should be a full, grammatically-correct sentence ending in a full stop.",
        "type": "string",
        "minLength": 2
      },
      "doi": {
        "description": "The DOI for the demo.",
        "type": "string"
      },
      "canonicalURL": {
        "description": "The canonical URL for the demo. Sometimes there might be more than one URL that points to a given page on a website. The canonical URL defines which of these should be thought of as the primary or main one.",
        "type": "string",
        "minLength": 10
      },
      "references": {
        "description": "An array of the references used for the demo.",
        "$ref": "./reference.schema.0.1.0.json"
      },
      "basedOnPapers": {
        "description": "An array of the DOIs for the papers the demo is based on. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "referencedByPapers": {
        "description": "An array of the DOIs of any papers that reference the demo. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "relatedContent": {
        "description": "An array of objects describing the content related to the demo. An empty array is allowed.",
        "$ref": "./related.content.schema.0.1.0.json"
      }
    },
    "required": [
      "title", "authors", "dateOfPublication", "dateOfLastModification", "categories", "tags", "previewImages", "seoDescription", "doi", "canonicalURL", "references", "basedOnPapers", "referencedByPapers", "relatedContent"
    ]
  }

=== PennyLaneAI/qml/demonstrations/tutorial_rotoselect.metadata.json
{
    "title": "Quantum circuit structure learning",
    "authors": [
        {
            "id": "angus_lowe"
        }
    ],
    "dateOfPublication": "2019-10-16T00:00:00",
    "dateOfLastModification": "2021-01-20T00:00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "rotoselect_structure.png"
        }
    ],
    "seoDescription": "",
    "doi": "",
    "canonicalURL": "https://pennylane.ai/qml/demos/tutorial_rotoselect.html",
    "references": [
        {
            "id": "",
            "title": "",
            "authors": "",
            "year": "",
            "journal": "",
            "doi": "",
            "url": ""
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_noise_models.metadata.json
{
    "title": "How to use noise models in PennyLane",
    "authors": [
        {
            "id": "utkarsh_azad"
        }
    ],
    "dateOfPublication": "2024-07-22T00:00:00+00:00",
    "dateOfLastModification": "2024-07-22T00:00:00+00:00",
    "categories": [
        "Quantum Computing"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/regular_demo_thumbnails/thumbnail_optimizing_noisy_circuits_Cirq.png"
        }
    ],
    "seoDescription": "Learn how noise models can be built and attached to a quantum circuit in PennyLane.",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_noise_models",
    "references": [
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_noisy_circuits",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_tensor_network_basics.json
{
    "title": "Introducing tensor networks for quantum practicioners",
    "authors": [
        {
            "username": "emiliano"
        },
        {
            "username": "ShiroRaven"
        }
    ],
    "dateOfPublication": "2024-08-06T00:00:00+00:00",
    "dateOfLastModification": "2024-08-06T00:00:00+00:00",
    "categories": [
        "Getting Started"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_tensor_network_basics.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_tensor_network_basics.png"
        }
    ],
    "seoDescription": "An introductory tutorial to tensor networks.",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_tn_basics",
    "references": [
        {
            "id": "huggins",
            "type": "article",
            "title": "Towards quantum machine learning with tensor networks",
            "authors": "W. Huggins, P. Patil, B. Mitchell, K. B. Whaley, and E. M. Stoudenmire",
            "year": "2019",
            "journal": "Quantum Science and Technology",
            "url": "http://dx.doi.org/10.1088/2058-9565/aaea94"
        },
        {
            "id": "orus",
            "type": "article",
            "title": "A practical introduction to tensor networks: Matrix product states and projected entangled pair states",
            "authors": "R. Or√∫s",
            "year": "2014",
            "journal": "Annals of Physics",
            "url": "https://www.sciencedirect.com/science/article/pii/S0003491614001596"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": []
}

=== PennyLaneAI/qml/demonstrations/guide_to_pennylane_knowing_qiskit.metadata.json
{
    "title": "Your Guide to PennyLane if You Know Qiskit",
    "authors": [
        {
            "id": "isaac_de_vlugt"
        }
    ],
    "dateOfPublication": "2024-07-01T00:00:00+00:00",
    "dateOfLastModification": "2024-07-01T00:00:00+00:00",
    "categories": [
        "Quantum Computing"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/zx_calculus/thumbnail_tutorial_zx_calculus.png"
        }
    ],
    "seoDescription": "This is your ultimate guide to PennyLane if you already know Qiskit.",
    "doi": "",
    "canonicalURL": "/qml/demos/ultimate_guide_to_pennylane_knowing_qiskit",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_qubit_rotation",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_local_cost_functions.metadata.json
{
    "title": "Alleviating barren plateaus with local cost functions",
    "authors": [
        {
            "id": "thomas_storwick"
        }
    ],
    "dateOfPublication": "2020-09-09T00:00:00",
    "dateOfLastModification": "2021-01-28T00:00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "tions/Cerezo_et_al_local_cost_functions.png"
        }
    ],
    "seoDescription": "",
    "doi": "",
    "canonicalURL": "https://pennylane.ai/qml/demos/tutorial_local_cost_functions.html",
    "references": [
        {
            "id": "",
            "title": "",
            "authors": "",
            "year": "",
            "journal": "",
            "doi": "",
            "url": ""
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/qonn.metadata.json
{
    "title": "Optimizing a quantum optical neural network",
    "authors": [
        {
            "id": "theodor_isacsson"
        }
    ],
    "dateOfPublication": "2020-08-05T00:00:00",
    "dateOfLastModification": "2022-03-08T00:00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "qonn_thumbnail.png"
        }
    ],
    "seoDescription": "",
    "doi": "",
    "canonicalURL": "https://pennylane.ai/qml/demos/qonn.html",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": []
}

=== PennyLaneAI/qml/demonstrations/tutorial_how_to_use_qiskit1.0_with_pennylane.metadata.json
{
    "title": "How to use Qiskit 1.0 with PennyLane",
    "authors": [
        {
            "id": "isaac_de_vlugt"
        }
    ],
    "dateOfPublication": "2024-06-25T00:00:00+00:00",
    "dateOfLastModification": "2024-06-25T00:00:00+00:00",
    "categories": [
        "Quantum Computing"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/TODO"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/TODO"
        }
    ],
    "seoDescription": "Learn how to get started using Qiskit 1.0 with PennyLane",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_how_to_use_qiskit1.0_with_pennylane",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_qubit_rotation",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_zx_calculus.metadata.json
{
    "title": "Introduction to the ZX-calculus",
    "authors": [
        {
            "id": "romain_moyard"
        }
    ],
    "dateOfPublication": "2023-06-06T00:00:00",
    "dateOfLastModification": "2023-06-06T00:00:00",
    "categories": [
        "Quantum Computing"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_images/thumbnail_tutorial_zx_calculus.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_zx_calculus.png"
        }
    ],
    "seoDescription": "Introduction to the ZX-calculus and use cases.",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_zx_calculus",
    "references": [
        {
            "id": "Coecke",
            "title": "Interacting Quantum Observables: Categorical Algebra and Diagrammatics.",
            "authors": "Bob Coecke and Ross Duncan.",
            "year": "2008",
            "publisher": "",
            "journal": "",
            "doi": "",
            "url": "https://arxiv.org/pdf/0906.4725.pdf"
        },
        {
            "id": "PyZX",
            "title": "PyZX GitHub.",
            "authors": "John van de Wetering.",
            "year": "",
            "publisher": "",
            "journal": "",
            "doi": "",
            "url": "https://github.com/Quantomatic/pyzx"
        },
        {
            "id": "East2021",
            "title": "AKLT-states as ZX-diagrams: diagrammatic reasoning for quantum states.",
            "authors": "Richard D. P. East, John van de Wetering, Nicholas Chancellor and Adolfo G. Grushin.",
            "year": "2021",
            "publisher": "",
            "journal": "",
            "doi": "",
            "url": "https://arxiv.org/pdf/2012.01219.pdf"
        },
        {
            "id": "JvdW2020",
            "title": "ZX-calculus for the working quantum computer scientist.",
            "authors": "John van de Wetering.",
            "year": "2020",
            "publisher": "",
            "journal": "",
            "doi": "",
            "url": "https://arxiv.org/abs/2012.13966"
        },
        {
            "id": "Zhao2021",
            "title": "Analyzing the barren plateau phenomenon in training quantum neural networks with the ZX-calculus.",
            "authors": "Chen Zhao and Xiao-Shan Gao.",
            "year": "2021",
            "publisher": "",
            "journal": "",
            "doi": "",
            "url": "https://quantum-journal.org/papers/q-2021-06-04-466/pdf/"
        },
        {
            "id": "Wang2022",
            "title": "Differentiating and Integrating ZX Diagrams with Applications to Quantum Machine Learning.",
            "authors": "Quanlong Wang, Richie Yeung, and Mark Koch.",
            "year": "2022",
            "publisher": "",
            "journal": "",
            "doi": "",
            "url": "https://arxiv.org/pdf/2201.13250.pdf"
        },
        {
            "id": "Duncan2020",
            "title": "Graph-theoretic Simplification of Quantum Circuits with the ZX-calculus.",
            "authors": "Ross Duncan, Aleks Kissinger, Simon Perdrix, and John van de Wetering.",
            "year": "2020",
            "publisher": "",
            "journal": "",
            "doi": "",
            "url": "https://quantum-journal.org/papers/q-2020-06-04-279/pdf/"
        },
        {
            "id": "Kissinger2021",
            "title": "Reducing T-count with the ZX-calculus.",
            "authors": "Aleks Kissinger and John van de Wetering.",
            "year": "2021",
            "publisher": "",
            "journal": "",
            "doi": "",
            "url": "https://quantum-journal.org/papers/q-2020-06-04-279/pdf/"
        },
        {
            "id": "Beaudrap2021",
            "title": "Circuit Extraction for ZX-diagrams can be #P-hard.",
            "authors": "Niel de Beaudrap, Aleks Kissinger and John van de Wetering.",
            "year": "2021",
            "publisher": "",
            "journal": "",
            "doi": "",
            "url": "https://arxiv.org/pdf/2202.09194.pdf"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_backprop",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_mbqc",
            "weight": 1.0
        }
    ]
}
