=== PennyLaneAI/qml/demonstrations/metadata_schemas/demo.metadata.schema.0.1.0.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/PennyLaneAI/qml/tree/master/demonstrations/metadata_schemas/demo.metadata.schema.0.1.0.json",
    "title": "Demo Metadata",
    "description": "A QML demo's metadata",
    "type": "object",
    "properties": {
      "title": {
        "description": "The title of the demo.",
        "type": "string",
        "minLength": 2
      },
      "authors": {
        "description": "The author(s) of the demo.",
        "type": "array",
        "items": {
          "$ref": "./author.schema.0.1.0.json"
        }
      },
      "dateOfPublication": {
        "description": "The date on which the demo was first published, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string"
      },
      "dateOfLastModification": {
        "description": "The date on which the demo was last modified, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string"
      },
      "categories": {
        "description": "An array of the categories that this demo is in.",
        "type": "array",
        "items": {
          "enum": ["Getting Started", "Optimization", "QML", "Quantum Chemistry", "Quantum Computing", "Community"]
        }
      },
      "tags": {
        "description": "An array of the tags that the demo has. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "previewImages": {
        "description": "An array of the different images that can be used as previews for this demo - e.g., thumbnails, social media cards (perhaps of different aspect ratios).",
        "$ref": "./preview.image.schema.0.1.0.json"
      },
      "seoDescription": {
        "description": "A description of the demo suitable for SEO purposes. Ideally this should be less than 150 characters, but this is not a strict limit. It should be a full, grammatically-correct sentence ending in a full stop.",
        "type": "string",
        "minLength": 2
      },
      "doi": {
        "description": "The DOI for the demo.",
        "type": "string"
      },
      "canonicalURL": {
        "description": "The canonical URL for the demo. Sometimes there might be more than one URL that points to a given page on a website. The canonical URL defines which of these should be thought of as the primary or main one.",
        "type": "string",
        "minLength": 10
      },
      "references": {
        "description": "An array of the references used for the demo.",
        "$ref": "./reference.schema.0.1.0.json"
      },
      "basedOnPapers": {
        "description": "An array of the DOIs for the papers the demo is based on. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "referencedByPapers": {
        "description": "An array of the DOIs of any papers that reference the demo. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "relatedContent": {
        "description": "An array of objects describing the content related to the demo. An empty array is allowed.",
        "$ref": "./related.content.schema.0.1.0.json"
      }
    },
    "required": [
      "title", "authors", "dateOfPublication", "dateOfLastModification", "categories", "tags", "previewImages", "seoDescription", "doi", "canonicalURL", "references", "basedOnPapers", "referencedByPapers", "relatedContent"
    ]
  }

=== PennyLaneAI/qml/demonstrations/tutorial_qaoa_intro.metadata.json
{
    "title": "Intro to QAOA",
    "authors": [
        {
            "id": "jack_ceroni"
        }
    ],
    "dateOfPublication": "2020-11-18T00:00:00",
    "dateOfLastModification": "2021-01-11T00:00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "qaoa_layer.png"
        }
    ],
    "seoDescription": "",
    "doi": "",
    "canonicalURL": "https://pennylane.ai/qml/demos/tutorial_qaoa_intro.html",
    "references": [
        {
            "id": "",
            "title": "",
            "authors": "",
            "year": "",
            "journal": "",
            "doi": "",
            "url": ""
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_here_comes_the_sun.metadata.json
{
    "title": "Here comes the SU(N): multivariate quantum gates and gradients",
    "authors": [
        {
            "id": "david_wierichs"
        }
    ],
    "dateOfPublication": "2023-04-03T00:00:00",
    "dateOfLastModification": "2023-04-03T00:00:00",
    "categories": [],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "https://pennylane.ai/qml/_images/thumbnail_tutorial_here_comes_the_sun.png"
        },
        {
            "type": "hero_image",
            "uri": "/_static/hero_illustrations/thumbnail_large_here_comes_the_sun.png"
        }
    ],
    "seoDescription": "Learn about multivariate quantum gates for optimization",
    "doi": "",
    "canonicalURL": "https://pennylane.ai/qml/demos/tutorial_here_comes_the_sun.html",
    "references": [
        {
            "id": "vatan",
            "title": "Optimal Quantum Circuits for General Two-Qubit Gates",
            "authors": "Farrokh Vatan and Colin Williams",
            "year": "2003",
            "publisher": "",
            "journal": "",
            "doi": "",
            "url": "https://arxiv.org/abs/quant-ph/0308006"
        },
        {
            "id": "wiersema",
            "title": "Here comes the SU(N): multivariate quantum gates and gradients",
            "authors": "R. Wiersema, D. Lewis, D. Wierichs, J. F. Carrasquilla, and N. Killoran",
            "year": "2023",
            "publisher": "",
            "journal": "",
            "doi": "",
            "url": "https://arxiv.org/abs/2303.11355"
        },
        {
            "id": "banchi",
            "title": "Measuring Analytic Gradients of General Quantum Evolution with the Stochastic Parameter Shift Rule.",
            "authors": "Leonardo Banchi and Gavin E. Crooks",
            "year": "2021",
            "publisher": "",
            "journal": "Quantum",
            "doi": "",
            "url": "https://quantum-journal.org/papers/q-2021-01-25-386/"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_vqe",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_general_parshift",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_unitary_designs",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_vqls.metadata.json
{
    "title": "Variational Quantum Linear Solver",
    "authors": [
        {
            "id": "andrea_mari"
        }
    ],
    "dateOfPublication": "2019-11-04T00:00:00",
    "dateOfLastModification": "2021-01-20T00:00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "vqls_zoom.png"
        }
    ],
    "seoDescription": "",
    "doi": "",
    "canonicalURL": "https://pennylane.ai/qml/demos/tutorial_vqls.html",
    "references": [
        {
            "id": "",
            "title": "",
            "authors": "",
            "year": "",
            "journal": "",
            "doi": "",
            "url": ""
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_initial_state_preparation.metadata.json
{
    "title": "Initial State Preparation for Quantum Chemistry",
    "authors": [
        {
            "id": "stepan_fomichev"
        }
    ],
    "dateOfPublication": "2023-10-20T00:00:00+00:00",
    "dateOfLastModification": "2024-08-05T00:00:00+00:00",
    "categories": [
        "Quantum Chemistry"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/initial_state_preparation/thumbnail_initial_state_preparation.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_initial_state_preparation.png"
        }
    ],
    "seoDescription": "Prepare initial states for quantum algorithms from output of traditional quantum chemistry methods.",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_initial_state_preparation",
    "references": [
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_quantum_chemistry",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_vqe",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_liesim2.metadata.json
{
    "title": "g-sim: Lie-algebraic classical simulations for variational quantum computing",
    "authors": [
        {
            "id": "korbinian_kottmann"
        }
    ],
    "dateOfPublication": "2024-05-29T00:00:00+00:00",
    "dateOfLastModification": "2024-05-29T00:00:00+00:00",
    "categories": [
        "Quantum Computing",
        "Getting Started"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/liesim/thumbnail_gsim.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_gsim.png"
        }
    ],
    "seoDescription": "A differentiable implementation of g-sim in PennyLane",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_liesim",
    "references": [
        {
            "id": "Wiersema",
            "type": "preprint",
            "title": "Classification of dynamical Lie algebras for translation-invariant 2-local spin systems in one dimension",
            "authors": "Roeland Wiersema, Efekan Kökcü, Alexander F. Kemper, Bojko N. Bakalov",
            "year": "2023",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2309.05690",
            "url": "https://arxiv.org/abs/2309.05690"
        },
        {
            "id": "Fontana",
            "type": "article",
            "title": "The Adjoint Is All You Need: Characterizing Barren Plateaus in Quantum Ansätze",
            "authors": "Enrico Fontana, Dylan Herman, Shouvanik Chakrabarti, Niraj Kumar, Romina Yalovetzky, Jamie Heredge, Shree Hari Sureshbabu, Marco Pistoia",
            "year": "2023",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2309.07902",
            "url": "https://arxiv.org/abs/2309.07902"
        },
        {
            "id": "Ragone",
            "type": "preprint",
            "title": "A Unified Theory of Barren Plateaus for Deep Parametrized Quantum Circuits",
            "authors": "Michael Ragone, Bojko N. Bakalov, Frédéric Sauvage, Alexander F. Kemper, Carlos Ortiz Marrero, Martin Larocca, M. Cerezo",
            "year": "2023",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2309.09342",
            "url": "https://arxiv.org/abs/2309.09342"
        },
        {
            "id": "Goh",
            "type": "preprint",
            "title": "Lie-algebraic classical simulations for variational quantum computing",
            "authors": "Matthew L. Goh, Martin Larocca, Lukasz Cincio, M. Cerezo, Frédéric Sauvage",
            "year": "2023",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2308.01432",
            "url": "https://arxiv.org/abs/2308.01432"
        },
        {
            "id": "Somma",
            "type": "preprint",
            "title": "Quantum Computation, Complexity, and Many-Body Physics",
            "authors": "Rolando D. Somma",
            "year": "2005",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.quant-ph/0512209",
            "url": "https://arxiv.org/abs/quant-ph/0512209"
        },
        {
            "id": "Somma2",
            "type": "preprint",
            "title": "Efficient solvability of Hamiltonians and limits on the power of some quantum computational models",
            "authors": "Rolando Somma, Howard Barnum, Gerardo Ortiz, Emanuel Knill",
            "year": "2006",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.quant-ph/0601030",
            "url": "https://arxiv.org/abs/quant-ph/0601030"
        },
        {
            "id": "Galitski",
            "type": "preprint",
            "title": "Quantum-to-Classical Correspondence and Hubbard-Stratonovich Dynamical Systems, a Lie-Algebraic Approach",
            "authors": "Victor Galitski",
            "year": "2010",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.1012.2873",
            "url": "https://arxiv.org/abs/1012.2873"
        },
        {
            "id": "Cerezo",
            "type": "preprint",
            "title": "Does provable absence of barren plateaus imply classical simulability? Or, why we need to rethink variational quantum computing",
            "authors": "M. Cerezo, Martin Larocca, Diego García-Martín, N. L. Diaz, Paolo Braccia, Enrico Fontana, Manuel S. Rudolph, Pablo Bermejo, Aroosa Ijaz, Supanut Thanasilp, Eric R. Anschuetz, Zoë Holmes",
            "year": "2023",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2312.09121",
            "url": "https://arxiv.org/abs/2312.09121"
        },
        {
            "id": "Mazzola",
            "type": "preprint",
            "title": "Quantum computing for chemistry and physics applications from a Monte Carlo perspective",
            "authors": "Guglielmo Mazzola",
            "year": "2023",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2308.07964",
            "url": "https://arxiv.org/abs/2308.07964"
        },
        {
            "id": "Park",
            "type": "preprint",
            "title": "Hardware-efficient ansatz without barren plateaus in any depth",
            "authors": "Chae-Yeun Park, Minhyeok Kang, Joonsuk Huh",
            "year": "2024",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2403.04844",
            "url": "https://arxiv.org/abs/2403.04844"
        }
    ],
    "basedOnPapers": ["10.48550/arXiv.2308.01432"],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_liealgebra",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_barren_plateaus",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_How_to_optimize_QML_model_using_JAX_and_Optax",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_teleportation.metadata.json
{
    "title": "Quantum Teleportation",
    "authors": [
        {
            "id": "matthew_silverman"
        }
    ],
    "dateOfPublication": "2023-10-20T00:00:00+00:00",
    "dateOfLastModification": "2024-01-01T00:00:00+00:00",
    "categories": [
        "Getting Started",
        "Quantum Computing"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/teleportation/thumbnail_teleportation.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_teleportation.png"
        }
    ],
    "seoDescription": "Transmit arbitrary quantum states using quantum teleportation",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_teleportation",
    "references": [
        {
            "id": "Teleportation1993",
            "type": "article",
            "title": "Teleporting an unknown quantum state via dual classical and Einstein-Podolsky-Rosen channels",
            "authors": "C. H. Bennett, G. Brassard, C. Cr√©peau, R. Jozsa, A. Peres, W. K. Wootters",
            "year": "1993",
            "publisher": "",
            "journal": "Phys. Rev. Lett.",
            "doi": "10.1103/PhysRevLett.70.1895",
            "url": "https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.70.1895"
        },
        {
            "id": "NandC2000",
            "type": "book",
            "title": "Quantum Computation and Quantum Information",
            "authors": "M. A. Nielsen, and I. L. Chuang",
            "year": "2000",
            "publisher": "Cambridge University Press",
            "journal": "",
            "url": ""
        },
        {
            "id": "Codebook",
            "type": "webpage",
            "title": "Xanadu Quantum Codebook",
            "authors": "C. Albornoz, G. Alonso, M. Andrenkov, P. Angara, A. Asadi, A. Ballon, S. Bapat, I. De Vlugt, O. Di Matteo, P. Finlay, A. Fumagalli, A. Gardhouse, N. Girard, A. Hayes, J. Izaac, R. Janik, T. Kalajdzievski, N. Killoran, J. Soni, D. Wakeham",
            "year": "2021",
            "publisher": "",
            "journal": "",
            "url": "https://codebook.xanadu.ai/I.15"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_zx_calculus",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_mbqc",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_vqe_qng.metadata.json
{
    "title": "Accelerating VQEs with quantum natural gradient",
    "authors": [
        {
            "id": "lana_bozanic"
        },
        {
            "id": "maggie_li"
        },
        {
            "id": "sukin_sim"
        }
    ],
    "dateOfPublication": "2020-11-06T00:00:00",
    "dateOfLastModification": "2021-04-08T00:00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "qng_example.png"
        }
    ],
    "seoDescription": "",
    "doi": "",
    "canonicalURL": "https://pennylane.ai/qml/demos/tutorial_vqe_qng.html",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": []
}

=== PennyLaneAI/qml/demonstrations/tutorial_how_to_create_dynamic_mcm_circuits.metadata.json
{
    "title": "How to create dynamic circuits with mid-circuit measurements",
    "authors": [
        {
            "id": "david_wierichs"
        }
    ],
    "dateOfPublication": "2024-05-03T00:00:00+00:00",
    "dateOfLastModification": "2024-05-03T00:00:00+00:00",
    "categories": [
        "Getting Started",
        "Quantum Computing"
    ],
    "tags": ["how to"],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/regular_demo_thumbnails/thumbnail_how_to_create_dynamic_mcm_circuits.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_how_to_create_dynamic_mcm_circuits.png"
        }
    ],
    "seoDescription": "Learn how to create dynamic circuits with control flow based on mid-circuit measurements.",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_how_to_create_dynamic_mcm_circuits",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_teleportation",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_mbqc",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_how_to_collect_mcm_stats",
            "weight": 1.0
        }
    ]
}
