=== PennyLaneAI/qml/metadata_schemas/demo.metadata.schema.0.1.0.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "demo.metadata.schema.0.1.0.json",
    "title": "Demo Metadata",
    "description": "A QML demo's metadata",
    "type": "object",
    "properties": {
      "title": {
        "description": "The title of the demo.",
        "type": "string",
        "minLength": 2
      },
      "authors": {
        "description": "The author(s) of the demo. This array must contain at least one item.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/author.schema.0.1.0.json"
        },
        "minItems": 1
      },
      "dateOfPublication": {
        "description": "The date on which the demo was first published, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string",
        "format": "date-time",
        "minLength": 25,
        "maxLength": 25
      },
      "dateOfLastModification": {
        "description": "The date on which the demo was last modified, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string",
        "format": "date-time",
        "minLength": 25,
        "maxLength": 25
      },
      "categories": {
        "description": "An array of the categories that this demo is in.",
        "type": "array",
        "items": {
          "enum": [
            "Algorithms",
            "Getting Started",
            "Optimization",
            "Quantum Machine Learning",
            "Quantum Chemistry",
            "Devices and Performance",
            "Quantum Computing",
            "Quantum Hardware"
          ]
        },
        "minItems": 0
      },
      "tags": {
        "description": "An array of the tags that the demo has. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "previewImages": {
        "description": "An array of the different images that can be used as previews for this demo - e.g., thumbnails, social media cards (perhaps of different aspect ratios).",
        "type": "array",
        "items": {
          "$ref": "file:./objects/preview.image.schema.0.1.0.json"
        },
        "minItems": 1
      },
      "seoDescription": {
        "description": "A description of the demo suitable for SEO purposes. Ideally this should be less than 150 characters, but this is not a strict limit. It should be a full, grammatically-correct sentence ending in a full stop.",
        "type": "string",
        "minLength": 2
      },
      "doi": {
        "description": "The DOI for the demo.",
        "type": "string",
        "pattern": "^$|^10[.]"
      },
      "canonicalURL": {
        "description": "The canonical URL for the demo. Sometimes there might be more than one URL that points to a given page on a website. The canonical URL defines which of these should be thought of as the primary or main one.",
        "type": "string",
        "pattern": "(^https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6})?\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)"
      },
      "references": {
        "description": "An array of the references used for the demo.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/reference.schema.0.1.0.json"
        }
      },
      "basedOnPapers": {
        "description": "An array of the DOIs for the papers the demo is based on. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "referencedByPapers": {
        "description": "An array of the DOIs of any papers that reference the demo. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "relatedContent": {
        "description": "An array of objects describing the content related to the demo. An empty array is allowed.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/related.content.schema.0.1.0.json"
        }
      }
    },
    "required": [
      "title", "authors", "dateOfPublication", "dateOfLastModification", "categories", "tags", "previewImages", "seoDescription", "doi", "canonicalURL", "references", "basedOnPapers", "referencedByPapers", "relatedContent"
    ]
  }

=== PennyLaneAI/qml/demonstrations/tutorial_intro_qrom.metadata.json
{
    "title": "Intro to quantum read-only memory (QROM)",
    "authors": [
        {
            "username": "KetPuntoG"
        },
        {
            "username": "ixfoduap"
        }
    ],
    "dateOfPublication": "2024-09-18T00:00:00+00:00",
    "dateOfLastModification": "2024-09-18T00:00:00+00:00",
    "categories": [
        "Algorithms",
        "Quantum Computing"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_qrom.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_qrom.png"
        }
    ],
    "seoDescription": "Learn how to enter data into a quantum computer with a quantum read-only memory (QROM) approach.",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_intro_qrom",
    "references": [
        {
        "id": "unary",
        "type": "article",
        "title": "Encoding Electronic Spectra in Quantum Circuits with Linear T Complexity",
        "authors": "Ryan Babbush, Craig Gidney, Dominic W. Berry, Nathan Wiebe, Jarrod McClean, Alexandru Paler, Austin Fowler, Hartmut Neven",
        "year": "2018",
        "publisher": "",
        "journal": "Physical Review X",
        "url": "http://dx.doi.org/10.1103/PhysRevX.8.041015"
    },
        {
        "id": "selectSwap",
        "type": "article",
        "title": "Trading T-gates for dirty qubits in state preparation and unitary synthesis",
        "authors": "Guang Hao Low, Vadym Kliuchnikov, Luke Schaeffer",
        "year": "2018",
        "publisher": "",
        "journal": "arXiv",
        "url": "https://arxiv.org/abs/1812.00954"
    },
        {
        "id": "cleanQROM",
        "type": "article",
        "title": "Qubitization of Arbitrary Basis Quantum Chemistry Leveraging Sparsity and Low Rank Factorization",
        "authors": "Dominic W. Berry, Craig Gidney, Mario Motta, Jarrod R. McClean, Ryan Babbush",
        "year": "2019",
        "publisher": "",
        "journal": "Quantum",
        "url": "http://dx.doi.org/10.22331/q-2019-12-02-208"
    },
        {
        "id": "StatePrep",
        "type": "article",
        "title": "Creating superpositions that correspond to efficiently integrable probability distributions",
        "authors": "Lov Grover, Terry Rudolph",
        "year": "2002",
        "publisher": "",
        "journal": "arXiv",
        "url": "https://arxiv.org/abs/quant-ph/0208112"
    }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_initial_state_preparation",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_liealgebra.metadata.json
{
    "title": "Evaluating analytic gradients of pulse programs on quantum computers",
    "authors": [
        {
            "id": "korbinian_kottmann"
        }
    ],
    "dateOfPublication": "2023-12-12T00:00:00+00:00",
    "dateOfLastModification": "2023-12-12T00:00:00+00:00",
    "categories": [
        "Optimization",
        "Quantum Computing",
        "Quantum Hardware"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/odegen/thumbnail_odegen.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_odegen.png"
        }
    ],
    "seoDescription": "Learn how to compute analytic gradients of pulse programs on quantum hardware",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_odegen",
    "references": [
        {
            "id": "Kottmann",
            "type": "preprint",
            "title": "Evaluating analytic gradients of pulse programs on quantum computers",
            "authors": "Korbinian Kottmann, Nathan Killoran",
            "year": "2023",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2309.16756",
            "url": "https://arxiv.org/abs/2309.16756"
        },
        {
            "id": "Krantz",
            "type": "article",
            "title": "Philip Krantz, Morten Kjaergaard, Fei Yan, Terry P. Orlando, Simon Gustavsson, William D. Oliver",
            "authors": "A Quantum Engineer's Guide to Superconducting Qubits",
            "year": "2019",
            "publisher": "",
            "journal": "J. Magn. Reson. 172, 296-305",
            "doi": "10.1063/1.5089550",
            "url": "https://arxiv.org/abs/1904.06560"
        },
        {
            "id": "Mitei",
            "type": "preprint",
            "title": "Gate-free state preparation for fast variational quantum eigensolver simulations: ctrl-VQE",
            "authors": "Oinam Romesh Meitei, Bryan T. Gard, George S. Barron, David P. Pappas, Sophia E. Economou, Edwin Barnes, Nicholas J. Mayhall",
            "year": "2020",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2008.04302",
            "url": "https://arxiv.org/abs/2008.04302"
        },
        {
            "id": "Banchi",
            "type": "article",
            "title": "Measuring Analytic Gradients of General Quantum Evolution with the Stochastic Parameter Shift Rule",
            "authors": "Leonardo Banchi, Gavin E. Crooks",
            "year": "2020",
            "publisher": "",
            "journal": "Quantum",
            "doi": "10.22331/q-2021-01-25-386",
            "url": "https://arxiv.org/abs/2005.10299",
            "preprint": "https://arxiv.org/abs/2005.10299"
        },
        {
            "id": "Leng",
            "type": "preprint",
            "title": "Differentiable Analog Quantum Computing for Optimization and Control",
            "authors": "Jiaqi Leng, Yuxiang Peng, Yi-Ling Qiao, Ming Lin, Xiaodi Wu",
            "year": "2022",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2210.15812",
            "url": "https://arxiv.org/abs/2210.15812",
            "preprint": "https://arxiv.org/abs/2210.15812"
        },
        {
            "id": "Patterson",
            "type": "preprint",
            "title": "Calibration of the cross-resonance two-qubit gate between directly-coupled transmons",
            "authors": "A. D. Patterson, J. Rahamim, T. Tsunoda, P. Spring, S. Jebari, K. Ratter, M. Mergenthaler, G. Tancredi, B. Vlastakis, M. Esposito, P. J. Leek",
            "year": "2019",
            "publisher": "",
            "journal": "Phys. Rev. Applied 12, 064013",
            "doi": "10.1103/PhysRevApplied.12.064013",
            "url": "https://doi.org/10.1103/PhysRevApplied.12.064013",
            "preprint": "https://arxiv.org/abs/1905.05670"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_pulse_programming101",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "oqc_pulse",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "ahs_aquila",
            "weight": 0.5
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/circuits_as_fourier_series.metadata.json
{
    "title": "Circuits as Fourier series",
    "authors": [
        {
            "id": "david_wakeham"
        }
    ],
    "dateOfPublication": "2023-06-26T00:00:00",
    "dateOfLastModification": "2023-06-26T00:00:00",
    "categories": [
        "Quantum Computing",
        "Optimization",
        "Quantum Machine Learning"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_images/thumbnail_tutorial_mitigation_advantage.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_mitigation_advantage.png"
        }
    ],
    "seoDescription": "TODO",
    "doi": "",
    "canonicalURL": "/qml/demos/circuits_as_fourier_series",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_expressivity_fourier_series",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_general_parshift",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_stochastic_parameter_shift",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_univariate_qvr.metadata.json
{
    "title": "Quantum detection of time series anomalies",
    "authors": [
        {
            "id": "jack_stephen_baker"
        },
        {
            "id": "santosh_kumar_radha"
        }
    ],
    "dateOfPublication": "2023-02-07T00:00:00+00:00",
    "dateOfLastModification": "2024-01-01T00:00:00+00:00",
    "categories": [
        "Quantum Machine Learning"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/univariate_qvr/thumbnail_tutorial_univariate_qvr.jpg"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_univariate_qvr.png"
        }
    ],
    "seoDescription": "Learn how to quantumly detect anomalous behaviour in time series data with the help of Covalent.",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_univariate_qvr",
    "references": [
        {
            "id": "Baker2022",
            "type": "article",
            "title": "Quantum Variational Rewinding for Time Series Anomaly Detection.",
            "authors": "Baker, Jack S. et al.",
            "year": "2022",
            "journal": "",
            "url": "https://arxiv.org/abs/2210.16438"
        },
        {
            "id": "Stone1932",
            "type": "article",
            "title": "On one-parameter unitary groups in Hilbert space.",
            "authors": "Stone, Marshall H.",
            "year": "1932",
            "journal": "Annals of Mathematics",
            "doi": "10.2307/1968538",
            "url": "https://doi.org/10.2307/1968538"
        },
        {
            "id": "Welch2014",
            "type": "article",
            "title": "Efficient quantum circuits for diagonal unitaries without ancillas",
            "authors": "Welch, Jonathan et al.",
            "year": "2014",
            "journal": "New Journal of Physics",
            "doi": "10.1088/1367-2630/16/3/033040",
            "url": "https://doi.org/10.1088/1367-2630/16/3/033040"
        },
        {
            "id": "Cîrstoiu2020",
            "type": "article",
            "title": "Variational fast forwarding for quantum simulation beyond the coherence time",
            "authors": "Cîrstoiu, Cristina et al.",
            "year": "2020",
            "journal": "npj Quantum Information",
            "doi": "10.1038/s41534-020-00302-0",
            "url": "https://doi.org/10.1038/s41534-020-00302-0"
        }
    ],
    "basedOnPapers": ["10.48550/arXiv.2210.16438"],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_qaoa_intro",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_qnn_module_torch.metadata.json
{
    "title": "Turning quantum nodes into Torch Layers",
    "authors": [
        {
            "username": "tombromleyxanadu"
        }
    ],
    "dateOfPublication": "2020-11-02T00:00:00+00:00",
    "dateOfLastModification": "2024-08-06T00:00:00+00:00",
    "categories": [
        "Devices and Performance",
        "Quantum Machine Learning"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_quantum_nodes_into_touch.png"
        }
    ],
    "seoDescription": "Learn how to create hybrid ML models in PennyLane using Torch",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_qnn_module_torch",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_qnn_module_tf",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_qpe.metadata.json
{
    "title": "Intro to Quantum Phase Estimation",
    "authors": [
        {
            "id": "juan_miguel_arrazola",
            "id": "guillermo_alonso"
        }
    ],
    "dateOfPublication": "2024-01-30T00:00:00+00:00",
    "dateOfLastModification": "2024-01-30T00:00:00+00:00",
    "categories": [
        "Algorithms",
        "Quantum Computing"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/qpe/thumbnail_Quantum_Phase_Estimation_2023-11-27.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_Quantum_Phase_Estimation_2023-11-27.png"
        }
    ],
    "seoDescription": "Master the basics of the quantum phase estimation",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_qpe",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": []
}

=== PennyLaneAI/qml/demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_catalyst_and_Optax.metadata.json
{
    "title": "How to optimize a QML model using Catalyst and quantum just-in-time (QJIT) compilation",
    "authors": [
        {
            "id": "josh_izaac"
        }
    ],
    "dateOfPublication": "2024-05-07T00:00:00+00:00",
    "dateOfLastModification": "2024-05-07T00:00:00+00:00",
    "categories": [
        "Quantum Machine Learning",
        "Optimization"
    ],
    "tags": ["how to"],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/regular_demo_thumbnails/thumbnail_how-to-optimize-qjit-optax.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_how-to-optimize-qjit-optax.png"
        }
    ],
    "seoDescription": "Learn how to train a quantum machine learning model using PennyLane, JAX, Catalyst, and Optax.",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_How_to_optimize_QML_model_using_JAX_catalyst_and_Optax",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_How_to_optimize_QML_model_using_JAX_and_Optax",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_jax_transformations",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_variational_classifier",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_equivariant_graph_embedding.metadata.json
{
    "title": "An equivariant graph embedding",
    "authors": [
        {
            "id": "maria_schuld"
        }
    ],
    "dateOfPublication": "2023-07-13T00:00:00+00:00",
    "dateOfLastModification": "2024-01-01T00:00:00+00:00",
    "categories": [
        "Quantum Machine Learning"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/equivariant_graph_embedding/thumbnail_tutorial_equivariant_graph_embedding.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_equivariant_graph_embedding.png"
        }
    ],
    "seoDescription": "Find out more about how to embedd graphs into quantum states.",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_equivariant_graph_embedding",
    "references": [
        {
            "id": "Skolik2022",
            "type": "article",
            "title": "Equivariant quantum circuits for learning on weighted graphs",
            "authors": "Andrea Skolik, Michele Cattelan, Sheir Yarkoni,Thomas Baeck and Vedran Dunjko",
            "year": "2022",
            "journal": "",
            "url": "https://arxiv.org/abs/2205.06109"
        },
        {
            "id": "Nguyen",
            "type": "article",
            "title": "Theory for Equivariant Quantum Neural Networks.",
            "authors": "Quynh T. Nguyen, Louis Schatzki, Paolo Braccia, Michael Ragone, Patrick J. Coles, Frédéric Sauvage, Martín Larocca and Marco Cerezo",
            "year": "2022",
            "journal": "",
            "url": "https://arxiv.org/abs/2210.08566"
        }
    ],
    "basedOnPapers": ["10.48550/arXiv.2205.06109"],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_geometric_qml",
            "weight": 1.0
        }
    ]
}
