=== PennyLaneAI/qml/metadata_schemas/demo.metadata.schema.0.1.0.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "demo.metadata.schema.0.1.0.json",
    "title": "Demo Metadata",
    "description": "A QML demo's metadata",
    "type": "object",
    "properties": {
      "title": {
        "description": "The title of the demo.",
        "type": "string",
        "minLength": 2
      },
      "authors": {
        "description": "The author(s) of the demo. This array must contain at least one item.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/author.schema.0.1.0.json"
        },
        "minItems": 1
      },
      "dateOfPublication": {
        "description": "The date on which the demo was first published, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string",
        "format": "date-time",
        "minLength": 25,
        "maxLength": 25
      },
      "dateOfLastModification": {
        "description": "The date on which the demo was last modified, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string",
        "format": "date-time",
        "minLength": 25,
        "maxLength": 25
      },
      "categories": {
        "description": "An array of the categories that this demo is in.",
        "type": "array",
        "items": {
          "enum": [
            "Algorithms",
            "Getting Started",
            "Optimization",
            "Quantum Machine Learning",
            "Quantum Chemistry",
            "Devices and Performance",
            "Quantum Computing",
            "Quantum Hardware"
          ]
        },
        "minItems": 0
      },
      "tags": {
        "description": "An array of the tags that the demo has. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "previewImages": {
        "description": "An array of the different images that can be used as previews for this demo - e.g., thumbnails, social media cards (perhaps of different aspect ratios).",
        "type": "array",
        "items": {
          "$ref": "file:./objects/preview.image.schema.0.1.0.json"
        },
        "minItems": 1
      },
      "seoDescription": {
        "description": "A description of the demo suitable for SEO purposes. Ideally this should be less than 150 characters, but this is not a strict limit. It should be a full, grammatically-correct sentence ending in a full stop.",
        "type": "string",
        "minLength": 2
      },
      "doi": {
        "description": "The DOI for the demo.",
        "type": "string",
        "pattern": "^$|^10[.]"
      },
      "canonicalURL": {
        "description": "The canonical URL for the demo. Sometimes there might be more than one URL that points to a given page on a website. The canonical URL defines which of these should be thought of as the primary or main one.",
        "type": "string",
        "pattern": "(^https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6})?\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)"
      },
      "references": {
        "description": "An array of the references used for the demo.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/reference.schema.0.1.0.json"
        }
      },
      "basedOnPapers": {
        "description": "An array of the DOIs for the papers the demo is based on. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "referencedByPapers": {
        "description": "An array of the DOIs of any papers that reference the demo. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "relatedContent": {
        "description": "An array of objects describing the content related to the demo. An empty array is allowed.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/related.content.schema.0.1.0.json"
        }
      }
    },
    "required": [
      "title", "authors", "dateOfPublication", "dateOfLastModification", "categories", "tags", "previewImages", "seoDescription", "doi", "canonicalURL", "references", "basedOnPapers", "referencedByPapers", "relatedContent"
    ]
  }

=== PennyLaneAI/qml/demonstrations/tutorial_phase_kickback.metadata.json
{
    "title": "Building a quantum lock using phase kickback",
    "authors": [
        {
            "id": "danial_motlagh"
        }
    ],
    "dateOfPublication": "2023-08-01T00:00:00+00:00",
    "dateOfLastModification": "2023-08-01T00:00:00+00:00",
    "categories": [
        "Getting Started",
        "Algorithms",
        "Quantum Computing"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_images/thumbnail_tutorial_phase_kickback.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_phase_kickback.png"
        }
    ],
    "seoDescription": "Use phase kickback to create an unbreakable quantum lock",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_phase_kickback",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_qubit_rotation",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_qft.metadata.json
{
    "title": "Intro to Quantum Fourier Transform",
    "authors": [
        {
            "id": "guillermo_alonso"
        }
    ],
    "dateOfPublication": "2024-01-30T00:00:00+00:00",
    "dateOfLastModification": "2024-01-30T00:00:00+00:00",
    "categories": [
        "Algorithms",
        "Quantum Computing"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/qpe/thumbnail_Quantum_Phase_Estimation_2023-11-27.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_Quantum_Phase_Estimation_2023-11-27.png"
        }
    ],
    "seoDescription": "Master the basics of the quantum fourier transform",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_qft",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": []
}

=== PennyLaneAI/qml/demonstrations/tutorial_lcu_blockencoding.metadata.json
{
    "title": "Linear combination of unitaries and block encodings",
    "authors": [
        {
            "id": "juan_miguel_arrazola"
        },
        {
            "id": "diego_guala"
        },
        {
            "id": "jay_soni"
        }
    ],
    "dateOfPublication": "2023-08-31T00:00:00+00:00",
    "dateOfLastModification": "2023-08-31T00:00:00+00:00",
    "categories": [
        "Algorithms",
        "Quantum Computing"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_images/thumbnail_tutorial_here_comes_the_sun.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_here_comes_the_sun.png"
        }
    ],
    "seoDescription": "Master the basics of LCUs and their applications",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_lcu_blockencoding",
    "references": [
        {
            "id": "qsvt",
            "type": "article",
            "title": "Quantum singular value transformation and beyond: exponential improvements for quantum matrix arithmetics",
            "authors": "András Gilyén, Yuan Su, Guang Hao Low, Nathan Wiebe",
            "year": "2019",
            "publisher": "",
            "journal": "",
            "url": "https://dl.acm.org/doi/abs/10.1145/3313276.3316366"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_intro_qsvt",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_apply_qsvt",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_contextuality.metadata.json
{
    "title": "Contextuality and inductive bias in QML",
    "authors": [
        {
            "id": "joseph_bowles"
        }
    ],
    "dateOfPublication": "2023-09-06T00:00:00+00:00",
    "dateOfLastModification": "2024-01-01T00:00:00+00:00",
    "categories": [
        "Quantum Machine Learning"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/contextuality/thumbnail_tutorial_Contextuality.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_Contextuality.png"
        }
    ],
    "seoDescription": "Train a problem-inspired ansatz on a contextuality-inspired dataset.",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_contextuality",
    "references": [
        {
            "id": "paper",
            "type": "article",
            "title": "Contextuality and inductive bias in quantum machine learning.",
            "authors": "J. Bowles, V. J. Wright, M. Farkas, N. Killoran, M. Schuld",
            "year": "2023",
            "journal": "",
            "url": "https://arxiv.org/abs/2302.01365"
        },
        {
            "id": "contextuality",
            "type": "article",
            "title": "Contextuality for preparations, transformations, and unsharp measurements.",
            "authors": "R. W. Spekkens",
            "year": "2005",
            "journal": "Phys. Rev. A 71",
            "url": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.71.052108"
        },
        {
            "id": "reptheory",
            "type": "article",
            "title": "Representation Theory for Geometric Quantum Machine Learning.",
            "authors": "M. Ragone, P. Braccia, Q. T. Nguyen, L. Schatzki, P. J. Coles, F. Sauvage, M. Larocca, M. Cerezo",
            "year": "2023",
            "journal": "",
            "url": "https://arxiv.org/abs/2210.07980"
        },
        {
            "id": "equivariant",
            "type": "article",
            "title": "Theory for Equivariant Quantum Neural Networks.",
            "authors": "Q. T. Nguyen, L. Schatzki, P. Braccia, M. Ragone, P. J. Coles, F. Sauvage, M. Larocca, M. Cerezo",
            "year": "2022",
            "journal": "",
            "url": "https://arxiv.org/abs/2210.08566"
        },
        {
            "id": "surrogates",
            "type": "article",
            "title": "Classical surrogates for quantum learning models.",
            "authors": "F. J. Schreiber, J. Eiser, J. J. Meyer",
            "year": "2022",
            "journal": "",
            "url": "https://arxiv.org/abs/2206.11740"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_geometric_qml",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/qrack.metadata.json
{
    "title": "QJIT compilation with Qrack and Catalyst",
    "authors": [
        {
            "id": "dan_strano"
        }
    ],
    "dateOfPublication": "2024-07-10T00:00:00+00:00",
    "dateOfLastModification": "2024-07-10T00:00:00+00:00",
    "categories": [
        "Devices and Performance"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/regular_demo_thumbnails/thumbnail_qrack_catalyst_integration.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_qrack_catalyst_integration.png"
        }
    ],
    "seoDescription": "Quantum JIT compilation (QJIT) using the Qrack device for PennyLane and Catalyst, with GPU-acceleration and novel optimization.",
    "doi": "",
    "canonicalURL": "/qml/demos/qrack",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_qft",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_clifford_circuit_simulations",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/gbs.metadata.json
{
    "title": "Quantum advantage with Gaussian Boson Sampling",
    "authors": [
        {
            "id": "josh_izaac"
        },
        {
            "id": "nathan_killoran"
        }
    ],
    "dateOfPublication": "2020-12-04T00:00:00+00:00",
    "dateOfLastModification": "2020-12-04T00:00:00+00:00",
    "categories": [
        "Quantum Hardware",
        "Quantum Computing"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/regular_demo_thumbnails/thumbnail_quantum_advantage_guassian_boson_sampling.png"
        }
    ],
    "seoDescription": "Using light to perform tasks beyond the reach of classical computers.",
    "doi": "",
    "canonicalURL": "/qml/demos/gbs",
    "references": [
        {
            "id": "Arute2019",
            "type": "article",
            "title": "Quantum supremacy using a programmable superconducting processor",
            "authors": "Arute, F., Arya, K., Babbush, R., et al.",
            "year": "2019",
            "journal": "Nature",
            "url": "https://doi.org/10.1038/s41586-019-1666-5"
        },
        {
            "id": "Zhong2020",
            "type": "article",
            "title": "Quantum computational advantage using photons",
            "authors": "Zhong, H.-S., Wang, H., Deng, Y.-H., et al.",
            "year": "2020",
            "journal": "Science",
            "doi": "10.1126/science.abe8770",
            "url": ""
        },
        {
            "id": "hamilton2017",
            "type": "article",
            "title": "Gaussian boson sampling",
            "authors": "Craig S. Hamilton, Regina Kruse, Linda Sansoni, Sonja Barkhofen, Christine Silberhorn, and Igor Jex",
            "year": "2017",
            "journal": "Physical Review Letters",
            "doi": "10.1103/PhysRevLett.119.170501",
            "url": ""
        },
        {
            "id": "aaronson2013",
            "type": "article",
            "title": "The computational complexity of linear optics",
            "authors": "Scott Aaronson and Alex Arkhipov",
            "year": "2013",
            "journal": "Theory of Computing",
            "doi": "10.4086/toc.2013.v009a004",
            "url": ""
        },
        {
            "id": "Bourassa2020",
            "type": "article",
            "title": "Blueprint for a scalable photonic fault-tolerant quantum computer",
            "authors": "Bourassa, J. E., Alexander, R. N., Vasmer, et al.",
            "year": "2020",
            "journal": "",
            "url": ""
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_gaussian_transformation",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "qsim_beyond_classical",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "qonn",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_photonics",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_mitigation_advantage.metadata.json
{
    "title": "Is quantum computing useful before fault tolerance?",
    "authors": [
        {
            "id": "korbinian_kottmann"
        }
    ],
    "dateOfPublication": "2023-06-16T00:00:00+00:00",
    "dateOfLastModification": "2023-06-16T00:00:00+00:00",
    "categories": [
        "Quantum Hardware",
        "Quantum Computing"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/mitigation_advantage/thumbnail_tutorial_mitigation_advantage.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_mitigation_advantage.png"
        }
    ],
    "seoDescription": "Using IBM's 127-qubit quantum computer to simulate deep quantum circuits using Zero Noise Extrapolation",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_mitigation_advantage",
    "references": [
        {
            "id": "ibm",
            "type": "article",
            "title": "Evidence for the utility of quantum computing before fault tolerance",
            "authors": "Youngseok Kim, Andrew Eddins, Sajant Anand, Ken Xuan Wei, Ewout van den Berg, Sami Rosenblatt, Hasan Nayfeh, Yantao Wu, Michael Zaletel, Kristan Temme & Abhinav Kandala",
            "year": "2023",
            "publisher": "Nature",
            "doi": "10.1038/s41586-023-06096-3",
            "url": "https://www.nature.com/articles/s41586-023-06096-3"
        },
        {
            "id": "PEC",
            "type": "article",
            "title": "Probabilistic error cancellation with sparse Pauli-Lindblad models on noisy quantum processors",
            "authors": "Ewout van den Berg, Zlatko K. Minev, Abhinav Kandala, Kristan Temme",
            "year": "2022",
            "publisher": "",
            "url": "https://arxiv.org/abs/2201.09866"
        }
    ],
    "basedOnPapers": ["10.1038/s41586-023-06096-3"],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_noisy_circuits",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "gbs",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_error_mitigation",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_diffable-mitigation",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_constant_depth_mps_prep.metadata.json
{
    "title": "Constant-depth preparation of matrix product states with dynamic circuits",
    "authors": [
        {
            "id": "david_wierichs"
        }
    ],
    "dateOfPublication": "2024-09-10T00:00:00+00:00",
    "dateOfLastModification": "2024-09-10T00:00:00+00:00",
    "categories": [
        "Quantum Computing",
        "Algorithms"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/regular_demo_thumbnails/thumbnail_constant_depth_mps_prep.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_constant_depth_mps_prep.png"
        }
    ],
    "seoDescription": "Prepare a matrix product state in constant depth with mid-circuit measurements and feedforward control.",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_constant_depth_mps_prep",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_mcm_introduction",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_how_to_create_dynamic_mcm_circuits",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_tn_circuits",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_initial_state_preparation",
            "weight": 1.0
        }
    ]
}
