=== PennyLaneAI/qml/metadata_schemas/demo.metadata.schema.0.1.0.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "demo.metadata.schema.0.1.0.json",
    "title": "Demo Metadata",
    "description": "A QML demo's metadata",
    "type": "object",
    "properties": {
      "title": {
        "description": "The title of the demo.",
        "type": "string",
        "minLength": 2
      },
      "authors": {
        "description": "The author(s) of the demo. This array must contain at least one item.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/author.schema.0.1.0.json"
        },
        "minItems": 1
      },
      "dateOfPublication": {
        "description": "The date on which the demo was first published, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string",
        "format": "date-time",
        "minLength": 25,
        "maxLength": 25
      },
      "dateOfLastModification": {
        "description": "The date on which the demo was last modified, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string",
        "format": "date-time",
        "minLength": 25,
        "maxLength": 25
      },
      "categories": {
        "description": "An array of the categories that this demo is in.",
        "type": "array",
        "items": {
          "enum": [
            "Algorithms",
            "Getting Started",
            "Optimization",
            "Quantum Machine Learning",
            "Quantum Chemistry",
            "Devices and Performance",
            "Quantum Computing",
            "Quantum Hardware"
          ]
        },
        "minItems": 0
      },
      "tags": {
        "description": "An array of the tags that the demo has. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "previewImages": {
        "description": "An array of the different images that can be used as previews for this demo - e.g., thumbnails, social media cards (perhaps of different aspect ratios).",
        "type": "array",
        "items": {
          "$ref": "file:./objects/preview.image.schema.0.1.0.json"
        },
        "minItems": 1
      },
      "seoDescription": {
        "description": "A description of the demo suitable for SEO purposes. Ideally this should be less than 150 characters, but this is not a strict limit. It should be a full, grammatically-correct sentence ending in a full stop.",
        "type": "string",
        "minLength": 2
      },
      "doi": {
        "description": "The DOI for the demo.",
        "type": "string",
        "pattern": "^$|^10[.]"
      },
      "canonicalURL": {
        "description": "The canonical URL for the demo. Sometimes there might be more than one URL that points to a given page on a website. The canonical URL defines which of these should be thought of as the primary or main one.",
        "type": "string",
        "pattern": "(^https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6})?\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)"
      },
      "references": {
        "description": "An array of the references used for the demo.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/reference.schema.0.1.0.json"
        }
      },
      "basedOnPapers": {
        "description": "An array of the DOIs for the papers the demo is based on. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "referencedByPapers": {
        "description": "An array of the DOIs of any papers that reference the demo. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "relatedContent": {
        "description": "An array of objects describing the content related to the demo. An empty array is allowed.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/related.content.schema.0.1.0.json"
        }
      }
    },
    "required": [
      "title", "authors", "dateOfPublication", "dateOfLastModification", "categories", "tags", "previewImages", "seoDescription", "doi", "canonicalURL", "references", "basedOnPapers", "referencedByPapers", "relatedContent"
    ]
  }

=== PennyLaneAI/qml/demonstrations/tutorial_learning2learn.metadata.json
{
    "title": "Learning to learn with quantum neural networks",
    "authors": [
        {
            "id": "stefano_mangini"
        }
    ],
    "dateOfPublication": "2021-03-02T00:00:00+00:00",
    "dateOfLastModification": "2023-08-28T00:00:00+00:00",
    "categories": [
        "Quantum Machine Learning"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_images/l2l_thumbnail.png"
        }
    ],
    "seoDescription": "Use a classical recurrent neural network to initilize the parameters of a variational quatum algorithm.",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_learning2learn",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_qaoa_intro",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_qaoa_maxcut",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_qsvt_hardware.metadata.json
{
    "title": "How to implement QSVT on hardware",
    "authors": [
        {
            "id": "guillermo_alonso"
        }
    ],
    "dateOfPublication": "2023-05-23T00:00:00+00:00",
    "dateOfLastModification": "2024-03-04T00:00:00+00:00",
    "categories": [
        "Algorithms",
        "Quantum Computing"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_qsvt_hardware.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_qsvt_hardware.png"
        }
    ],
    "seoDescription": "Learn how to implement QSVT on hardware.",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_qsvt_hardware",
    "references": [
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_intro_qsvt",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_apply_qsvt",
            "weight": 1.0
        }

    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_how_to_quantum_just_in_time_compile_vqe_catalyst.metadata.json
{
    "title": "How to quantum just-in-time compile VQE with Catalyst",
    "authors": [
        {
            "id": "josh_izaac"
        }
    ],
    "dateOfPublication": "2024-05-07T00:00:00+00:00",
    "dateOfLastModification": "2024-05-07T00:00:00+00:00",
    "categories": [
        "Quantum Machine Learning",
        "Optimization",
        "Quantum Chemistry"
    ],
    "tags": ["how to"],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/regular_demo_thumbnails/thumbnail_brief_overview_of_VQE.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_How_to_optimize_QML_model_using_JAX_and_Optax_2024-01-16.png"
        }
    ],
    "seoDescription": "Learn how to find the ground state of a molecule with VQE using PennyLane, Catalyst, and just-in-time compilation.",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_how_to_quantum_just_in_time_compile_vqe_catalyst.ipynb",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_How_to_optimize_QML_model_using_JAX_catalyst_and_Optax",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_vqe",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_learningshallow.metadata.json
{
    "title": "Learning shallow quantum circuits with local inversions and circuit sewing",
    "authors": [
        {
            "id": "korbinian_kottmann"
        }
    ],
    "dateOfPublication": "2024-01-24T00:00:00+00:00",
    "dateOfLastModification": "2024-01-24T00:00:00+00:00",
    "categories": [
        "Optimization",
        "Quantum Computing",
        "Quantum Machine Learning"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/learningshallow/thumbnail_learningshallow.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_learningshallow.png"
        }
    ],
    "seoDescription": "Learn how to do circuit sewing with local inversions, which play a crucial role in learning shallow quantum circuits",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_learningshallow",
    "references": [
        {
            "id": "Huang",
            "type": "preprint",
            "title": "Learning shallow quantum circuits",
            "authors": "Hsin-Yuan Huang, Yunchao Liu, Michael Broughton, Isaac Kim, Anurag Anshu, Zeph Landau, Jarrod R. McClean",
            "year": "2024",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2401.10095",
            "url": "https://arxiv.org/abs/2401.10095"
        },
        {
            "id": "Bravyi",
            "type": "preprint",
            "title": "Sergey Bravyi, David Gosset, Robert Koenig",
            "authors": "Quantum advantage with shallow circuits",
            "year": "2017",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.1704.00690",
            "url": "https://arxiv.org/abs/1704.00690"
        },
        {
            "id": "Anschuetz",
            "type": "preprint",
            "title": "Beyond Barren Plateaus: Quantum Variational Algorithms Are Swamped With Traps",
            "authors": "Eric R. Anschuetz, Bobak T. Kiani",
            "year": "2022",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2205.05786",
            "url": "https://arxiv.org/abs/2205.05786"
        },
        {
            "id": "Shende",
            "type": "article",
            "title": "Synthesis of Quantum Logic Circuits",
            "authors": "Vivek V. Shende, Stephen S. Bullock, Igor L. Markov",
            "year": "2004",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.quant-ph/0406176",
            "url": "https://arxiv.org/abs/quant-ph/0406176"
        }
    ],
    "basedOnPapers": [
        "10.48550/arXiv.2401.10095"
    ],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_How_to_optimize_QML_model_using_JAX_and_JAXopt",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_Post_Variational_Quantum_Neural_Networks.metadata.json
{
    "title": "Post Variational Quantum Neural Networks",
    "authors": [
        {
            "id": "elaina_zhu"
        },
        {
            "id": "po_wei_huang"
        }
    ],
    "dateOfPublication": "2023-04-03T00:00:00+00:00",
    "dateOfLastModification": "2024-01-01T00:00:00+00:00",
    "categories": [
        "Quantum Machine Learning"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/here_comes_the_sun/thumbnail_tutorial_here_comes_the_sun.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_here_comes_the_sun.png"
        }
    ],
    "seoDescription": "Learn about multivariate quantum gates for optimization",
    "doi": "",
    "canonicalURL": "/qml/demos/Post_Variational_Quantum_Neural_Networks",
    "references": [
        {
            "id": "cerezo2021variational",
            "type": "article",
            "title": "Variational quantum algorithms",
            "authors": "M. Cerezo and Andrew Arrasmith and Ryan Babbush and Simon C. Benjamin and Suguru Endo and Keisuke Fujii and Jarrod R. McClean and Kosuke Mitarai and Xiao Yuan and Lukasz Cincio and Patrick J. Coles",
            "year": "2021",
            "publisher": "Springer Science and Business Media LLC",
            "journal": "Nature Reviews Physics",
            "doi": "10.1038/s42254-021-00348-9",
            "url": "https://doi.org/10.1038/s42254-021-00348-9"
        },
        {
            "id": "mcclean2018barren",
            "type": "article",
            "title": "Barren plateaus in quantum neural network training landscapes",
            "authors": "Jarrod R. McClean and Sergio Boixo and Vadim N. Smelyanskiy and Ryan Babbush and Hartmut Neven",
            "year": "2018",
            "journal": "Nature Communications",
            "doi": "10.1038/s41467-018-07090-4"
        },
        {
            "id": "du2020expressive",
            "type": "article",
            "title": "Expressive power of parametrized quantum circuits",
            "authors": "Du, Yuxuan and Hsieh, Min-Hsiu and Liu, Tongliang and Tao, Dacheng",
            "year": "2020",
            "publisher": "American Physical Society",
            "journal": "Phys. Rev. Res.",
            "doi": "10.1103/PhysRevResearch.2.033125",
            "url": "https://link.aps.org/doi/10.1103/PhysRevResearch.2.033125"
        },
        {
            "id": "schuld2019evaluating",
            "type": "article",
            "title": "Evaluating analytic gradients on quantum hardware",
            "authors": "Schuld, Maria and Bergholm, Ville and Gogolin, Christian and Izaac, Josh and Killoran, Nathan",
            "year": "2019",
            "journal": "Phys. Rev. A",
            "doi": "10.1103/PhysRevA.99.032331",
            "url": "https://doi.org/10.1103/PhysRevA.99.032331"
        },
        {
            "id": "huang2024postvariational",
            "type": "article",
            "title": "Post-variational quantum neural networks",
            "authors": "Po-Wei Huang and Patrick Rebentrost",
            "year": "2024",
            "doi": "10.48550/arXiv.2307.10560",
            "url": "https://arxiv.org/pdf/2307.10560"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": []
}

=== PennyLaneAI/qml/demonstrations/tutorial_learning_dynamics_incoherently.metadata.json
{
    "title": "Learning Dynamics Incoherently",
    "authors": [
        {
            "id": "diego_guala"
        }
    ],
    "dateOfPublication": "2024-07-09T00:00:00+00:00",
    "dateOfLastModification": "2024-07-09T00:00:00+00:00",
    "categories": [
        "Quantum Machine Learning"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/regular_demo_thumbnails/thumbnail_learning_dynamics_incoherently.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_learning_dynamics_incoherently.png"
        }
    ],
    "seoDescription": "Learning Dynamics Incoherently",
    "doi": "",
    "canonicalURL": "/qml/demos/learning_dynamics_incoherently",
    "references": [
        {
            "id": "jerbi2023power",
            "type": "article",
            "title": "The power and limitations of learning quantum dynamics incoherently",
            "authors": "Sofiene Jerbi, Joe Gibbs, Manuel S. Rudolph, Matthias C. Caro, Patrick J. Coles, Hsin-Yuan Huang, and ZoÃ« Holmes",
            "year": "2023",
            "url": "https://arxiv.org/abs/2303.12834"
        }
    ],
    "basedOnPapers": ["10.48550/arXiv.2303.12834"],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_haar_measure",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_eqnn_force_field.metadata.json
{
    "title": "Symmetry-invariant quantum machine learning force fields",
    "authors": [
        {
            "id": "oriel_kiss"
        }
    ],
    "dateOfPublication": "2024-01-20T00:00:00+00:00",
    "dateOfLastModification": "2024-01-20T00:00:00+00:00",
    "categories": [
        "Quantum Machine Learning", "Quantum Chemistry"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/EQNN-FF/overview.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_eqnn-force-field.png"
        }
    ],
    "seoDescription": "Learn about equivariant quantum machine learning for chemistry",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_eqnn-force-field",
    "references": [
        {
            "id": "Le",
            "type": "article",
            "title": "Symmetry-invariant quantum machine learning force fields",
            "authors": "Isabel Nha Minh Le, Oriel Kiss, Julian Schuhmacher, Ivano Tavernelli and Francesco Tacchino",
            "year": "2023",
            "publisher": "",
            "journal": "",
            "url": "https://arxiv.org/abs/2311.11362"
        },
        {
            "id": "kiss",
            "type": "article",
            "title": "Quantum neural networks force fields generation",
            "authors": "Oriel Kiss, Francesco Tacchino, Sofia Vallecorsa and Ivano Tavernelli",
            "year": "2023",
            "publisher": "IOP",
            "journal": " Mach. Learn.: Sci. Technol.",
            "url": "https://iopscience.iop.org/article/10.1088/2632-2153/ac7d3c"
        },
        {
            "id": "schuld",
            "type": "article",
            "title": "Effect of data encoding on the expressive power of variational quantum-machine-learning models",
            "authors": "Maria Schuld, Ryan Sweke, and Johannes Jakob Meyer",
            "year": "2021",
            "publisher": "APS",
            "journal": "Phys. Rev. A",
            "url": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.103.032430"
        } ,
        {
            "id": "wierichs",
            "type": "article",
            "title": "Symmetric derivatives of parametrized quantum circuits",
            "authors": "David Wierichs, Richard D. P. East, Mart√≠n Larocca, M. Cerezo and Nathan Killoran",
            "year": "2023",
            "publisher": "",
            "journal": "",
            "url": "https://arxiv.org/abs/2312.06752"
        } ,
        {
            "id": "meyer",
            "type": "article",
            "title": "Exploiting Symmetry in Variational Quantum Machine Learning",
            "authors": "Johannes Jakob Meyer, Marian Mularski, Elies Gil-Fuster, Antonio Anna Mele, Francesco Arzani, Alissa Wilms, and Jens Eisert",
            "year": "2023",
            "publisher": "APS",
            "journal": "Phys. Rev. X Quantum",
            "url": "https://journals.aps.org/prxquantum/abstract/10.1103/PRXQuantum.4.010328"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_expressivity_fourier_series",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_geometric_qml",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_contextuality",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/qml/demonstrations/tutorial_neutral_atoms.metadata.json
{
    "title": "Neutral-atom quantum computers",
    "authors": [
        {
            "id": "alvaro_ballon"
        }
    ],
    "dateOfPublication": "2023-05-30T00:00:00+00:00",
    "dateOfLastModification": "2023-05-30T00:00:00+00:00",
    "categories": [
        "Quantum Hardware",
        "Quantum Computing"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/neutral_atoms/thumbnail_tutorial_neutral_atoms.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/large_demo_thumbnails/thumbnail_large_neutral_atoms.png"
        }
    ],
    "seoDescription": "Learn how neutral atom quantum devices work using code.",
    "doi": "",
    "canonicalURL": "/qml/demos/tutorial_neutral_atoms",
    "references": [
        {
            "id": "Aquila2022",
            "type": "webpage",
            "title": "Aquila, our 256-qubit quantum processor.",
            "authors": "Quera",
            "year": "2023",
            "journal": "",
            "url": "https://www.quera.com/aquila"
        },
        {
            "id": "DiVincenzo2000",
            "type": "article",
            "title": "The Physical Implementation of Quantum Computation.",
            "authors": "DiVincenzo",
            "year": "2000",
            "journal": "Fortschritte der Physik 48",
            "url": "https://arxiv.org/abs/quant-ph/0002077"
        },
        {
            "id": "Tweezers1985",
            "type": "article",
            "title": "Observation of a single-beam gradient force optical trap for dielectric particles.",
            "authors": "A. Ashkin, J. M. Dziedzic, J. E. Bjorkholm, and Steven Chu.",
            "year": "1986",
            "journal": "",
            "url": ""
        },
        {
            "id": "AtomComputing",
            "type": "webpage",
            "title": "Quantum Computing Technology.",
            "authors": "Atom Computing",
            "year": "2023",
            "journal": "",
            "url": "https://atom-computing.com/quantum-computing-technology"
        },
        {
            "id": "Neutral2020",
            "type": "article",
            "title": "Quantum computing with neutral atoms.",
            "authors": "L. Henriet, et al.",
            "year": "2020",
            "journal": "Quantum volume",
            "url": "https://arxiv.org/abs/2006.12326"
        },
        {
            "id": "Pulser2022",
            "type": "article",
            "title": "Pulser: An open-source package for the design of pulse sequences in programmable neutral-atom arrays.",
            "authors": "H. Silverio et al.",
            "year": "2022",
            "journal": "Quantum volume",
            "url": "https://arxiv.org/abs/2104.15044"
        },
        {
            "id": "Morgado2011",
            "type": "article",
            "title": "Quantum simulation and computing with Rydberg-interacting qubits",
            "authors": "M. Morgado and S. Whitlock.",
            "year": "2021",
            "journal": "AVS Quantum Sci.",
            "url": "https://arxiv.org/abs/2011.03031"
        },
        {
            "id": "NeutralHardware2023",
            "type": "article",
            "title": "Neutral Atom Quantum Computing Hardware: Performance and End-User Perspective.",
            "authors": "K. Wintersperger et al.",
            "year": "2023",
            "journal": "",
            "url": "https://arxiv.org/abs/2304.14360"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_pasqal",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "ahs_aquila",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_pulse_programming101",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_trapped_ions",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_sc_qubits",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_photonics",
            "weight": 1.0
        }
    ]
}
